server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/account_db
  kafka:
    bootstrap-servers: kafka:9092
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://keycloak:8080/realms/banking/protocol/openid-connect/certs}
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://keycloak:8080/realms/banking}

banking:
  redis:
    enabled: true
    host: redis
